### ISSUE TITLE
MMCV_Custom 

### ISSUE THREAD

**Issue by cxq1** [HDETR/H-Deformable-DETR#1]
Hi, thank you for your work. I would like to ask how MMCV_Custom can be used in MMDetection's own project. I want to use the AMP acceleration in MMDetection, I wonder if it is feasible

**Comment by PkuRainBow** [comment]
Thanks for your interest! We would like to release the support of HDETR on MMDetection soon. Please stay tuned.

@JiaDingCN

**Comment by cxq1** [comment]
Thank you for you reply

**Comment by PkuRainBow** [comment]
https://github.com/HDETR/H-Deformable-DETR-mmdet

**Comment by cxq1** [comment]
> @cxq1 https://github.com/HDETR/H-Deformable-DETR-mmdet


Thank you for you reply
