### ISSUE TITLE
Will the AP improve if i use fp16?

### ISSUE THREAD

**Issue by hotcore** [HDETR/H-Deformable-DETR#10]
Will the AP improve if i use fp16?
Will fp16  slow down training, takes more time?
i have a v100 32g,i set batch=4
i really don't know that...

**Comment by PkuRainBow** [comment]
FP16 will not improve the performance.

FP16 can accelerate training to some degree.

**Comment by jihwanp** [comment]
@PkuRainBow  As im using this repo to train hybrid matching, the training  time per iteration is almost three times more than the original deformable detr with 1800 queries. (original:0.6s/iter and hybrid matching 1.8s/iter with same batch size and GPU) What makes training so slow?
(Im using this config file, _two_stage/deformable-detr-hybrid-branch/12eps/r50_hybrid_branch_lambda1_group6_t1500_deformable_detr_plus_iterative_bbox_refinement_plus_plus_two_stage.sh_ with dim_feedfoward set to 1024)

And there seems to be no difference in learning speed even if I use fp16.

Can u please double check this

**Comment by hotcore** [comment]
> FP16 will not improve the performance.
> 
> FP16 can accelerate training to some degree.

thks  for ur reply~
appreciate❤️

**Comment by PkuRainBow** [comment]
@jihwanp We will release an optimized implementation that runs faster. Please stay patient.
