### ISSUE TITLE
Question about variant of hybrid matching

### ISSUE THREAD

**Issue by jihwanp** [HDETR/H-Deformable-DETR#11]
Hi I have a question about the performance of hybrid matching scheme.
As you noticed that among the 3 different hybrid matching schemes, using hybrid branch seems work well and achieve faster inference time since only 300 queries are used compared to other ones.
In my knowledge, if using two stage DDETR , we can set different number of queries at training and test time, so if you don't mind, I want to know whether there is potential performance degradation if training other variants with large number of queries and test with fewer queries with two stage architecture.

Thanks!

**Comment by PkuRainBow** [comment]
Thanks for your interest in our work!

As we use a mixed query selection scheme, we could not change the number of queries during inference as a fixed set of learnable parameters cannot be interpolated to some degree.

The two variant hybrid matching schemes are mainly used to prove our approach's effectiveness and generalization ablitiy.

**Comment by jihwanp** [comment]
Thanks for your comment. 
I've recently see your ablation about the influence of K, and I'm curious why small K (1,2) results worse performance than original. Also u stated in the paper that **careful selection mechanism can achieve consistent gains even when using K=1**, what is that selection mechanism?

**Comment by PkuRainBow** [comment]
@jihwanp We will update the arxiv in the near future, which includes more details of the above mentioned "careful selection mechanism".
