### ISSUE TITLE
Question about weight decay

### ISSUE THREAD

**Issue by hotcore** [HDETR/H-Deformable-DETR#17]
man i saw your chart weight decay=0.05 under the normal weight=1e-4,  weight decay=0.05 has better performance.
but its just on swin backbone in the table,
Will it better on the renset backbone with weight decay=0.05?
hope ur reply~

**Comment by PkuRainBow** [comment]
It is a good practice to use larger weight decay (stronger regularization) for the transformer-based backbones. So we guess this might not help for Conv-based backbones.

**Comment by hotcore** [comment]
> It is a good practice to use larger weight decay (stronger regularization) for the transformer-based backbones. So we guess this might not help for Conv-based backbones.

ok，i got it~ 
appreciate !!
