### ISSUE TITLE
Questions about the DETR's performance

### ISSUE THREAD

**Issue by ddwhzh** [HDETR/H-Deformable-DETR#18]
Thank you very much for your work.
Because the experiments were conducted on DDETR, I would like to know if this training strategy has any enhancement to the original DETR? 
And I have some care for the growth of its training GPU memory usage. 
If you have the corresponding data then thank you very much.

**Comment by PkuRainBow** [comment]
@ddwhzh Thanks for your interest. We will include more details on the concern on the training GPU memory consumption in the arXiv revision soon.

In general, the additional memory consumption is mild.

**Comment by ddwhzh** [comment]
THX
