### ISSUE TITLE
The shape of outputs_classses_one2_many is 0!

### ISSUE THREAD

**Issue by rockywind** [HDETR/H-Deformable-DETR#2]
Thanks for sharing such wonderful & interesting work!!!
When I run the code, I met the error below.
![image](https://user-images.githubusercontent.com/14838781/184052871-13848ddb-bbf5-4eba-b697-fbc7b5f29bf2.png)

**Comment by PkuRainBow** [comment]
@rockywind  If you meet any other problems, please feel free to reopen this issue.
