### ISSUE TITLE
How can I apply this code to other datasets?

### ISSUE THREAD

**Issue by AWGiaGia** [HDETR/H-Deformable-DETR#20]
The complete COCO dataset is too large for me as I only have a single 8GiB graphics card, and training on it would take too long. How can I modify this code to train or test on my own dataset?
I apologize for asking such a foolish question, and I have great admiration for the work your team has done.
However, I noticed that the dataset path in the code is set to 'coco_path'. Does this mean that if I want to train on a different dataset, I would need to put a lot of effort into adjusting the structure of the existing code?

**Comment by AWGiaGia** [comment]
> 

Sincerely thanks.
Does this mean that I can train on other, smaller coco datasets without having to make too many adjustments?

**Comment by HichTala** [comment]
I think so, the only thing you need to pay attention to is that your dataset is in Coco format, which means that the annotations are in the same format and the file is organized like COCO2017, i.e. as follows :

```
coco_path/
  ├── train2017/
  ├── val2017/
  └── annotations/
  	├── instances_train2017.json
  	└── instances_val2017.json
```

**Comment by AWGiaGia** [comment]
Thank you !@HichTala
