### ISSUE TITLE
Hello, this tricks contains those details.

### ISSUE THREAD

**Issue by sorrowyn** [HDETR/H-Deformable-DETR#4]
![图片](https://user-images.githubusercontent.com/19569162/187629250-4be19f88-3e03-4e32-a45d-96fff29a8be5.png)

**Comment by YanShuang17** [comment]
Refer to `Table 9` in arxiv paper

**Comment by sorrowyn** [comment]
![图片](https://user-images.githubusercontent.com/19569162/189833597-3bdea91f-1b67-4c1a-acb2-31b819cd856f.png)
Thank you for the kind tip!
