### ISSUE TITLE
The total batch size

### ISSUE THREAD

**Issue by jshilong** [HDETR/H-Deformable-DETR#6]
Thanks for your awesome work!
But I do not find key information in the paper and the released code. What is the total batch size of H-DETR, 32 or 16?

Thanks!

**Comment by PkuRainBow** [comment]
https://github.com/HDETR/H-Deformable-DETR/blob/10af735b13bb1f28ae391fd4a3926285662b0af3/main.py#L48 

We train all the models with a batch size of 16 (2 images/GPU x 8 GPUs) as we do not have access to rich GPU resources.
