### ISSUE TITLE
About Hybrid-Layer Implement

### ISSUE THREAD

**Issue by wisematch** [HDETR/H-Deformable-DETR#7]
Thank you for your great work and well-organized repo.
However, I do not find any code for the variant scheme Hybrid epoch or Hybrid layer. How did you implement Hybrid layer? Are there two decoders, and calculate losses separately?

**Comment by PkuRainBow** [comment]
Thanks for your interest in our work.

We will release the code for the hybrid epoch and the hybrid layer scheme. Considering the trade-off between the overall training cost and the detection performance, we encourage you to try our hybrid branch scheme.
