### ISSUE TITLE
LVIS configs

### ISSUE THREAD

**Issue by HanGuangXin** [HDETR/H-Deformable-DETR#8]
Hi, could you please provide the configs on LVIS dataset? Appreciate it!

**Comment by PkuRainBow** [comment]
Thanks for your interest in our work.

@hardyho will prepare and release the related code soon.

**Comment by HanGuangXin** [comment]
@hardyho Hi, is there any progress?

**Comment by PkuRainBow** [comment]
@HanGuangXin Please keep patient! We plan to release the related code of LVIS in the short future. Thanks for your understanding!

**Comment by PkuRainBow** [comment]
https://github.com/HDETR/H-Detic-LVIS 

@HanGuangXin
